/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsWidget: typeof import('./src/components/AnalyticsWidget.vue')['default']
    AutomationLogsWidget: typeof import('./src/components/AutomationLogsWidget.vue')['default']
    BackupStatusWidget: typeof import('./src/components/BackupStatusWidget.vue')['default']
    Badge: typeof import('./src/components/ui/badge.vue')['default']
    BaseWidget: typeof import('./src/components/widgets/BaseWidget.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    CalendarWidget: typeof import('./src/components/CalendarWidget.vue')['default']
    Card: typeof import('./src/components/ui/card.vue')['default']
    DashboardContent: typeof import('./src/components/DashboardContent.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DashboardNavigation: typeof import('./src/components/DashboardNavigation.vue')['default']
    DockerStatsWidget: typeof import('./src/components/DockerStatsWidget.vue')['default']
    ForceGraph: typeof import('./src/components/ForceGraph.vue')['default']
    MediaStatsWidget: typeof import('./src/components/MediaStatsWidget.vue')['default']
    MediaStatsWidgetTMDB: typeof import('./src/components/MediaStatsWidgetTMDB.vue')['default']
    NetworkStatus: typeof import('./src/components/NetworkStatus.vue')['default']
    NetworkTopologyWidget: typeof import('./src/components/NetworkTopologyWidget.vue')['default']
    Progress: typeof import('./src/components/ui/progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityAlertsWidget: typeof import('./src/components/SecurityAlertsWidget.vue')['default']
    SettingsWidget: typeof import('./src/components/SettingsWidget.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton.vue')['default']
    Slider: typeof import('./src/components/ui/slider.vue')['default']
    SmartHomeWidget: typeof import('./src/components/SmartHomeWidget.vue')['default']
    StatusPill: typeof import('./src/components/StatusPill.vue')['default']
    Switch: typeof import('./src/components/ui/switch.vue')['default']
    SystemGraphs: typeof import('./src/components/SystemGraphs.vue')['default']
    SystemGraphsWidget: typeof import('./src/components/SystemGraphsWidget.vue')['default']
    ThemeDropdown: typeof import('./src/components/ThemeDropdown.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    WeatherPill: typeof import('./src/components/WeatherPill.vue')['default']
  }
}
