version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - vscode-insiders-extensions:/home/vscode/.vscode-server-insiders/extensions
      - dotnet-tools:/home/vscode/.dotnet/tools
      - node-modules:/workspace/frontend/node_modules
      - nuget-packages:/home/vscode/.nuget/packages
    working_dir: /workspace
    command: sleep infinity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
      - "5000:5000"
      - "7026:7026"
      - "7443:7443"
    privileged: true
    init: true
    networks:
      - devcontainer

  # Optional: Add a database for testing
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nexus_home_link
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devcontainer

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - devcontainer

volumes:
  vscode-extensions:
  vscode-insiders-extensions:
  dotnet-tools:
  node-modules:
  nuget-packages:
  postgres-data:

networks:
  devcontainer:
    driver: bridge
